import type { Metadata, Viewport } from "next";
import { DM_Sans } from "next/font/google";
import { ToastContainer } from "@/components/toast";
import "./globals.css";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  themeColor: "#0a0a0a",
};

export const metadata: Metadata = {
  title: {
    default: "Provador Virtual | Paradise - Experimente Roupas com IA",
    template: "%s | Paradise Provador Virtual",
  },
  description:
    "Experimente roupas da Paradise no seu corpo com inteligencia artificial. Envie sua foto, escolha pecas do catalogo e veja o resultado em menos de 2 minutos. 100% gratuito.",
  keywords: [
    "provador virtual",
    "experimentar roupa online",
    "try on virtual",
    "paradise multimarcas",
    "moda masculina",
    "IA moda",
    "provador com inteligencia artificial",
  ],
  authors: [{ name: "Paradise" }],
  creator: "Paradise",
  metadataBase: new URL("https://provador.useparadise.com.br"),
  alternates: {
    canonical: "/",
  },
  openGraph: {
    title: "Provador Virtual | Paradise",
    description:
      "Veja como a roupa fica no seu corpo antes de comprar. Resultado com IA em menos de 2 minutos.",
    type: "website",
    url: "https://provador.useparadise.com.br",
    siteName: "Paradise Provador Virtual",
    locale: "pt_BR",
    // OG image auto-generated by opengraph-image.tsx
    images: ["/opengraph-image"],
  },
  twitter: {
    card: "summary_large_image",
    title: "Provador Virtual | Paradise",
    description: "Veja como a roupa fica no seu corpo antes de comprar.",
    images: ["/opengraph-image"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <link rel="icon" href="/icon.png" type="image/png" />
      </head>
      <body className={`${dmSans.variable} font-sans bg-[#0a0a0a] text-white antialiased`}>
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
